.github/ISSUE_TEMPLATE/issue_template.md, .github/pull_request_template.md
Creação do template de issue e pull request
Esse pr resolve a issue #1 
- Criar template de issue
- Criar template de pull request
=> Create issue and pull request template

docs/README.md, docs/index.html, docs/planning/team_planning.md, docs/styling/accessibility.md, docs/styling/style_guide.md
Nesse pr, temos o ajuste na composição da aba de estilização, onde segregamos a acessibilidade do guia de estilo
#3 
- Ajustar página de acessibilidade
=> Ajuste da página de acessibilidade

docs/planning/team_planning.md
Neste pull request, foram documentadas as metodologias decidas pelo grupo
#9 
- Esclarecer metodologias escolhidas
- Porque, como e quando utiliza-las
- Documentação estar no GH Pages
=> Metodologia

LICENSE
Criação da licença
#30 - Adicionar Licença
- Adicionar licença
=> #30 Create license

docs/planning/evaluated_sites.md
Nesta branch foi criado o documento que descreve os sites avaliados individualmente por cada membro do grupo, além de uma breve contextualização da escolha do SEI como objeto de estudo principal.
#17 - Lista de sites avaliados
- Escrita da lista de sites
- Escrita da descrição de cada site
- Contextualização da escolha do sei
=> Lista de sites avaliados

docs/evaluation/project_general_principles.md
Esse pr contempla a criação dos princípios gerais do projeto que visa documentar a razões que guiaram a refatoração da plataforma 
#11 
-  Criar princípios
- Descreve-los
- Estar no GHPages
=> Princípios gerais do projeto

docs/evaluation/usability_goals.md
Este PR visa acrescentar a documentação sobre as metas de usabilidade na _wiki_ do projeto.
#8 
- Definição superficial das metas
- Explicação das metas
=> Documentar as metas de usabilidade

docs/_sidebar.md, docs/meeting/PC1/sprint_0.md, docs/meeting/PC1/sprint_1.md, docs/meeting/PC2/sprint_2.md, docs/planning/evaluated_sites.md, docs/styling/accessibility.md, docs/styling/style_guide.md
Documentar sprint 0 e sprint 1
Criação dos documentos sobre as atas das reuniões sobre o ponto de controle 1
#23 
-  Documentar Sprint 0
- Documentar Sprint 1
=> Documentar sprint 0 e sprint 1

docs/_sidebar.md, docs/meeting/PC1/professor_meeting_1.md
Esse pr inclue um documento que detalha a reunião que tivemos com o professor
#24
-  Sintetizar conclusão tomada pelo grupo
- Documentar reunião
=> Documentar reunião com o professor

docs/_sidebar.md, docs/meeting/PC1/pc1_presentation.md, docs/meeting/PC1/professor_meeting_1.md
Co-authored-by: Leonardo Gomes <leonardodasigomes@gmail.com>
Estruturação do documento para incluir o vídeo do primeiro ponto de controle
#10 - Ponto de Controle 1
- Criação da apresentação em vídeo
- Ajuste nos links dos vídeos
=> apresentação do PC1

docs/use_context/tasks_analysis.md
Documento de Análise de Tarefas
#35 
- Análise de tarefas do site
- Documentação da análise
=> Adding tasks analysis content

docs/_sidebar.md, docs/meeting/PC1/sprint_0.md, docs/meeting/PC1/sprint_1.md, docs/meeting/PC2/sprint_2.md, docs/meeting/PC2/sprint_3.md
o pull request tem como finalidade apresentar na nossa wiki a ata de reunião
#47 
-  Documentar Sprint 3
=> Criação do documento da sprint 3

docs/evaluation/project_general_principles.md, docs/planning/project_planning.md, docs/planning/team_planning.md, docs/styling/accessibility.md, docs/styling/style_guide.md
Ajustes nos pontos que o professor levantou a necessidade de melhoria
#44 - Feedback do professor
- Adição de comentário nas figuras
- Adição do UXPressia como ferramenta
- Ajuste no texto do processo de design
- Atualização da data de entrega de tarefas
=> 44 professor feedback

docs/planning/platform_features.md
O documento de características da plataforma foi escrito apresentando as principais funcionalidades e contratempos da plataforma, bem como seus objetivos.
#36 
- Apresentação dos objetivos da plataforma
- Apresentação das funcionalidades _core_
- Apresentação das telas relacionadas as funcionalidades
=> Características da plataforma

docs/use_context/tasks_analysis.md
Refatoração do documento de Análise de Tarefas
#35 
* Escolha das tarefas analisadas
*  Elaborar diagrama de funcionalidades
*  Documentação estar no GH Pages
=> New tasks analysis

docs/_sidebar.md, docs/meeting/PC2/pc2_presentation.md
O vídeo produzido foi sintetizado e documentado dentro da nossa wiki
#48 - Apresentação da PC2
- Criação dos slides
- Gravação do vídeo
- Publicação do vídeo
- Documentação no repositório
=> Criação do doc da apresentação do PC2

docs/_sidebar.md, docs/meeting/PC2/sprint_3.md, docs/meeting/PC3/pc3_presentation.md, docs/meeting/PC3/sprint_4.md, docs/meeting/PC3/sprint_5.md, docs/planning/project_planning.md
Preparar o repo para a PC3
- Criação do doc para a PC3
- Documentação das sprints que não estavam no repositório
- Inclusão de mais datas de entregas no planejamento
=> Ponto de Controle 3

docs/_sidebar.md, docs/accessibility/WCAG.md, docs/accessibility/accessibility.md, docs/evaluation/heuristic_evaluation.md, docs/evaluation/project_general_principles.md, docs/evaluation/storyboard/consent_form.md, docs/evaluation/storyboard/planning.md, docs/evaluation/task_analysis/consent_form.md, docs/evaluation/task_analysis/planning.md, docs/evaluation/usability_goals.md, docs/meeting/PC1/professor_meeting_1.md, docs/meeting/PC1/sprint_0.md, docs/meeting/PC1/sprint_1.md, docs/meeting/PC2/sprint_2.md, docs/meeting/PC2/sprint_3.md, docs/meeting/PC3/sprint_4.md, docs/meeting/PC3/sprint_5.md, docs/meeting/PC4/pc4_presentation.md, docs/meeting/PC5/sprint_8.md, docs/meeting/PC5/sprint_9.md, docs/planning/evaluated_sites.md, docs/planning/platform_features.md, docs/planning/project_planning.md, docs/planning/team_planning.md, docs/styling/style_guide.md, docs/use_context/personas.md, docs/use_context/storyboards.md, docs/use_context/tasks_analysis.md, docs/use_context/user_profiles.md
Reorganização geral do repositório
Issues que foram resolvidas com o PR
- Ajuste na sidebar
- Criação de documento de ponto de controle
- Atualização das datas de entrega
- Documentação de novas sprints
=> refatoração do repositório

docs/_sidebar.md, docs/evaluation/low_fidelity_prototype/results.md
Resultados da avaliação do protótipo de baixa fidelidade 
#70 
- Entrevista Piloto
- Entrevista 1
- Entrevista 2
- Entrevista 3
- Conclusão
=> 70 enterview of paper prototype

docs/_navbar.md, docs/_sidebar.md, docs/evaluation/high_fidelity_prototype/results.md, docs/evaluation/low_fidelity_prototype/results.md, docs/meeting/PC5/pc5_presentation.md, docs/meeting/PC6/pc6_presentation.md, docs/meeting/PC7/pc7_presentation.md, docs/planning/project_planning.md, docs/redesign_artefacts/high_fidelity_prototype.md, docs/use_context/storyboards.md
Descrição concisa do que foi feito
Issues que foram resolvidas com o PR
- Tarefa 1
- Tarefa 2
=> High fidelity prototype
